### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by irxbacon** [vtrhyno/SEBC#1]

**Comment by irxbacon** [comment]
I couldn't get replication to work and moved on.  I now believe its because of port issues I was having but will likely not get it working before morning.

Manager installation is hung between unpacked and activated.

**Comment by mikeridley** [comment]
I wasn't getting my notifications on issues so I'm just seeing this now.  Are you still having problems?

**Comment by mfernest** [comment]
@mikeridley please evaluate

**Comment by mikeridley** [comment]
Comments:
1_prechecks does not include anything on verify noatime for mounted filesystems.  This may have been verified but I don't see any note about it.  Also, in 1_prechecks I see OpenJDK being installed but you want to avoid OpenJDK with Hadoop, since it won't work.

Overall, everything else looks good to me.

**Comment by mfernest** [comment]
Call it a borderline C(omplete). OpenJDK is a no-go choice and I'm sure you had to fix it. I wanted to see it called out in the Issue when you correct something that was called out.
